source $HOME/.zgen/zgen.zsh

# Custom oh-my-zsh confiuration
DEFAULT_USER="jauer"
DISABLE_AUTO_TITLE="true"
DISABLE_AUTO_UPDATE="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="dd.mm.yyyy"

# Build zgen cache if necessary
if ! zgen saved; then
	# Load oh-my-zsh
	zgen oh-my-zsh

	# Bundles from oh-my-zsh
	zgen oh-my-zsh plugins/cargo
	zgen oh-my-zsh plugins/common-aliases
	zgen oh-my-zsh plugins/colored-man-pages
	zgen oh-my-zsh plugins/extract
	zgen oh-my-zsh plugins/gitfast
	zgen oh-my-zsh plugins/github
	zgen oh-my-zsh plugins/rust
	zgen oh-my-zsh plugins/z

	# Other third-party plugins
	zgen load zsh-users/zsh-syntax-highlighting

	# OS specific plugins
	if [[ "$OSTYPE" == "linux-gnu" ]]; then

	elif [[ "$OSTYPE" == "darwin"* ]]; then
		zgen oh-my-zsh plugins/brew
		zgen oh-my-zsh plugins/osx
	elif [[ "$OSTYPE" == "cygwin" ]]; then
		zgen oh-my-zsh plugins/cygwin
	fi

	# Own settings and overrides
	zgen load jan-auer/zsh-multiline multiline

	# Save the plugins
	zgen save
fi

# Set environment behavior
export PAGER="less -FRX"
export EDITOR=vim
export VISUAL=vim

# Revert cp, mv and rm to default
# Commands are probably aliased by oh-my-zsh
unalias cp 2> /dev/null
unalias mv 2> /dev/null
unalias rm 2> /dev/null

# Prevent python bytecode
export PYTHONDONTWRITEBYTECODE=1

# Create a new directory and enter it
# From https://github.com/mathiasbynens/dotfiles
function mkd() {
	mkdir -p "$@" && cd "$_";
}

