#!/usr/bin/env zsh

# Custom oh-my-zsh confiuration
DEFAULT_USER="jauer"
DISABLE_AUTO_TITLE="true"
DISABLE_AUTO_UPDATE="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="dd.mm.yyyy"

# Load zgen after initializing variables
source $HOME/.zgen/zgen.zsh

# Build zgen cache if necessary
if ! zgen saved; then
	# Load oh-my-zsh
	zgen oh-my-zsh

	# Bundles from oh-my-zsh
	zgen oh-my-zsh plugins/cargo
	zgen oh-my-zsh plugins/common-aliases
	zgen oh-my-zsh plugins/colored-man-pages
	zgen oh-my-zsh plugins/extract
	zgen oh-my-zsh plugins/fzf
	zgen oh-my-zsh plugins/gitfast
	zgen oh-my-zsh plugins/github
	zgen oh-my-zsh plugins/virtualenv
	zgen oh-my-zsh plugins/z

	# Other third-party plugins
	zgen load zsh-users/zsh-syntax-highlighting
	zgen load andrewferrier/fzf-z

	# OS specific plugins
	if [[ "$OSTYPE" == "linux-gnu" ]]; then

	elif [[ "$OSTYPE" == "darwin"* ]]; then
		zgen oh-my-zsh plugins/macos
	elif [[ "$OSTYPE" == "cygwin" ]]; then
		zgen oh-my-zsh plugins/cygwin
	fi

	# Own settings and overrides
	zgen load jan-auer/zsh-multiline multiline

	# Save the plugins
	zgen save
fi

# Tune history settings
setopt hist_ignore_all_dups      # Delete old recorded entry if new entry is a duplicate.
setopt hist_reduce_blanks        # Remove superfluous blanks before recording entry.

# Set the term language
export LANG=en
export LC_COLLATE=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_MESSAGES=en_US.UTF-8
export LC_MONETARY=de_DE.UTF-8
export LC_NUMERIC=de_DE.UTF-8
export LC_TIME=de_DE.UTF-8

# Set environment behavior
export PAGER="less -FRX"
export EDITOR=vim
export VISUAL=vim

# Revert cp, mv and rm to default
# Commands are probably aliased by oh-my-zsh
unalias cp 2> /dev/null
unalias mv 2> /dev/null
unalias rm 2> /dev/null
unalias fd 2> /dev/null

# Create a new directory and enter it
# From https://github.com/mathiasbynens/dotfiles
function mkd() {
	mkdir -p "$@" && cd "$_";
}

# Load fzf completion and key bindings
export FZF_DEFAULT_OPTS="--no-height"
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
alias f=fzf

if [ "$(echo $COLORFGBG | cut -d ';' -f2)" -gt 8 ]; then
	export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS --color light"
fi

# Prevent python bytecode
export PYTHONDONTWRITEBYTECODE=1

# Lazily load virtualenvwrapper to improve startup time
if [ -s /usr/local/bin/virtualenvwrapper_lazy.sh ]; then
	source /usr/local/bin/virtualenvwrapper_lazy.sh
fi

# Configure bat defaults
if (( $+commands[bat] )); then
	if [ "$(echo $COLORFGBG | cut -d ';' -f2)" -gt 8 ]; then
		export BAT_THEME="Solarized (light)"
	else
		export BAT_THEME="Solarized (dark)"
	fi
	export BAT_STYLE=plain
	alias cat=bat
fi

# Configure volta (Node version manager)
export VOLTA_HOME="$HOME/.volta"
[ -s "$VOLTA_HOME/load.sh" ] && . "$VOLTA_HOME/load.sh"
export PATH="$VOLTA_HOME/bin:$PATH"

# Create a new Google Meet and open in the browser
function meet {
	if [ -n "$1" ]; then
		local authuser="?authuser=$1"
	fi
	open "https://meet.google.com/new$authuser"
}

if [ -s /opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc ]; then
	source /opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc
fi
