source $HOME/.zgen/zgen.zsh

# Custom oh-my-zsh confiuration
DEFAULT_USER="jauer"
DISABLE_AUTO_TITLE="true"
DISABLE_AUTO_UPDATE="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="dd.mm.yyyy"

# Build zgen cache if necessary
if ! zgen saved; then
	# Load oh-my-zsh
	zgen oh-my-zsh

	# Bundles from oh-my-zsh
	zgen oh-my-zsh plugins/cargo
	zgen oh-my-zsh plugins/common-aliases
	zgen oh-my-zsh plugins/colored-man-pages
	zgen oh-my-zsh plugins/extract
	zgen oh-my-zsh plugins/gitfast
	zgen oh-my-zsh plugins/github
	zgen oh-my-zsh plugins/rust
	zgen oh-my-zsh plugins/virtualenv
	zgen oh-my-zsh plugins/z

	# Other third-party plugins
	zgen load zsh-users/zsh-syntax-highlighting
	zgen load andrewferrier/fzf-z
	zgen load marzocchi/zsh-notify

	# OS specific plugins
	if [[ "$OSTYPE" == "linux-gnu" ]]; then

	elif [[ "$OSTYPE" == "darwin"* ]]; then
		zgen oh-my-zsh plugins/osx
	elif [[ "$OSTYPE" == "cygwin" ]]; then
		zgen oh-my-zsh plugins/cygwin
	fi

	# Own settings and overrides
	zgen load jan-auer/zsh-multiline multiline

	# Save the plugins
	zgen save
fi

# Tune history settings
setopt hist_ignore_all_dups      # Delete old recorded entry if new entry is a duplicate.
setopt hist_reduce_blanks        # Remove superfluous blanks before recording entry.

# Set environment behavior
export PAGER="less -FRX"
export EDITOR=vim
export VISUAL=vim

# Revert cp, mv and rm to default
# Commands are probably aliased by oh-my-zsh
unalias cp 2> /dev/null
unalias mv 2> /dev/null
unalias rm 2> /dev/null
unalias fd 2> /dev/null

# Create a new directory and enter it
# From https://github.com/mathiasbynens/dotfiles
function mkd() {
	mkdir -p "$@" && cd "$_";
}

# Load fzf completion and key bindings
export FZF_CTRL_R_OPTS='--no-preview'
FZF_PREVIEW='[[ $(file -bI {} | cut -d/ -f1) == "text" ]] && bat -n --line-range 1:$LINES --color always {} || file -b {}'
export FZF_DEFAULT_OPTS="--margin 1,0 --no-height --no-reverse --preview-window up:75% --preview '$FZF_PREVIEW'"
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
source ~/.fzf.zsh
alias f=fzf

# Prevent python bytecode
export PYTHONDONTWRITEBYTECODE=1

# Lazily load virtualenvwrapper to improve startup time
source /usr/local/bin/virtualenvwrapper_lazy.sh

# Lazy load nvm
export NVM_DIR="$HOME/.nvm"
if [ -s "$NVM_DIR/nvm.sh" ]; then
	function nvm {
		if [ -z $NVM_LAZY_LOADED ]; then
			source "$NVM_DIR/nvm.sh"
			NVM_LAZY_LOADED=true
		fi
		nvm "$@"
	}
fi

# Prepend certain keg-only brew formulae to the PATH
formulae=(
	postgresql@9.6
	redis@3.2
)

for formula in $formulae; do
	export PATH="/usr/local/opt/$formula/bin:$PATH"
done

# Configure bat defaults
export BAT_PAGER=less
export BAT_THEME=TwoDark
alias cat=bat
